In [13]:
import numpy as np

# Question 1

A = np.array([[2, -1, 3],
             [0, 4, 1]])
print("Matrix A:", A)
print('\n')
print('Shape of Matrix A:', A.shape)
print('\n')

B = np.array([[1, 2],[-2, 0],
             [5, -3]])
print("Matrix B:", B)
print('\n')
print('Shape of Matrix B:', B.shape)
print('\n')





Matrix A: [[ 2 -1  3]
 [ 0  4  1]]


Shape of Matrix A: (2, 3)


Matrix B: [[ 1  2]
 [-2  0]
 [ 5 -3]]


Shape of Matrix B: (3, 2)




In [ ]:
# Question 2

''' After checking the dimension of the two matrix, 
Number of rows in matrix A is equal to Number of columns in matrix B. 
So the matrix AB is defined.(we can multiply it)


After checking the dimension of the two matrix, 
Number of rows in matrix B is equal to Number of columns in matrix A. 
So the matrix BA is defined.(we can multiply it)

After checking the dimension of the two matrix, 
Number of rows in matrix AB is not equal to Number of columns in matrix BA. 
So the matrix AB != BA is not defined.(we can not multiply it)

'''

In [ ]:
# Question 3

Mat_mult_1 = np.dot(A, B)
print("The matrix multiplication of (A and B) = \n", Mat_mult_1)
print('\n')
print('The shape of matrix AB = ', Mat_mult_1.shape)
print('\n')


Mat_mult_2 = np.dot(B, A)
print("The matrix multiplication of (B and A) = \n", Mat_mult_2)
print('\n')
print('The shape of matrix BA = ', Mat_mult_2.shape)
print('\n')

print('since the two matrix has different shape then Matrix AB != Matrix BA')



The matrix multiplication of (A and B) = 
 [[19 -5]
 [-3 -3]]


The shape of matrix AB =  (2, 2)


The matrix multiplication of (B and A) = 
 [[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]


The shape of matrix BA =  (3, 3)


Matrix AB != Matrix BA
