In [110]:
import numpy as np

# Question 1

# create 4 x 3 matrix 
scores = np.array([[80, 70, 90],[60, 85, 75], 
                  [95, 88, 92], [70, 60, 65]])
print("Student scores in a matrix:\n", scores)



Student scores in a matrix:
 [[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]


In [111]:
print("Total score for each (student_1, student_2, student_3, student_4) :", np.sum(scores, axis=1))  
print("\n")
print("Student_1_score:", np.sum(scores[:1]))
print("\n")
print("Student_2_score:", np.sum(scores[1:2]))
print("\n")
print("Student_3_score:", np.sum(scores[2:3]))
print("\n")
print("Student_4_score:", np.sum(scores[3:4]))

Total score for each (student_1, student_2, student_3, student_4) : [240 220 275 195]


Student_1_score: 240


Student_2_score: 220


Student_3_score: 275


Student_4_score: 195


In [112]:
scores = scores.copy()
scalar_math = 2

scores[:, 0] = scalar_math * scores[:, 0]
print("Student scores:\n", scores)

Student scores:
 [[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]


In [113]:
print("Average score for each (Math, English, Science) :", np.mean(scores, axis=0))  

Average score for each (Math, English, Science) : [152.5   75.75  80.5 ]


In [114]:

weight_vector = np.array([[0.5], [0.3], [0.2]])
final_grades = scores @ weight_vector
#final_grade = np.dot(scores, weight_vector)
print("The final_grades:", final_grades)

The final_grades: [[119. ]
 [100.5]
 [139.8]
 [101. ]]


In [115]:
scores

array([[160,  70,  90],
       [120,  85,  75],
       [190,  88,  92],
       [140,  60,  65]])

In [35]:
student_1_score = scores[0:1]
student_2_score = scores[1:2]

print("Student_1 Score vector:",student_1_score)
print("\n")
print("Student_2 Score vector:",student_2_score)

compare_scores = student_1_score - student_2_score
print("\n")
print("comparing student (1 & 2) vector score", compare_scores)

Student_1 Score vector: [[160  70  90]]


Student_2 Score vector: [[120  85  75]]


comparing student (1 & 2) vector score [[ 40 -15  15]]


In [99]:
# Question 2


new_scores = np.array([[82, 71, 77, 55],[50, 45, 79, 82], 
                  [59, 68, 72, 53], [30, 70, 55, 64], [72, 83, 65, 87]])
print("Student scores in a matrix:", new_scores)

Student scores in a matrix: [[82 71 77 55]
 [50 45 79 82]
 [59 68 72 53]
 [30 70 55 64]
 [72 83 65 87]]


In [100]:
new_scores.shape

(5, 4)

In [101]:
print("Total score for each (student_1, student_2, student_3, student_4, student_5) :", np.sum(new_scores, axis=1)) 

print("\n")
print("Student_1_score:", np.sum(new_scores[:1]))
print("\n")
print("Student_2_score:", np.sum(new_scores[1:2]))
print("\n")
print("Student_3_score:", np.sum(new_scores[2:3]))
print("\n")
print("Student_4_score:", np.sum(new_scores[3:4]))
print("\n")
print("Student_5_score:", np.sum(new_scores[4:5]))

Total score for each (student_1, student_2, student_3, student_4, student_5) : [285 256 252 219 307]


Student_1_score: 285


Student_2_score: 256


Student_3_score: 252


Student_4_score: 219


Student_5_score: 307


In [103]:
print("Average score for each (Math, English, Science, chemistry) :", np.mean(new_scores, axis=0)) 

Average score for each (Math, English, Science, chemistry) : [58.6 67.4 69.6 68.2]


In [104]:
new_scores = new_scores.copy()
scalar_science = 3

new_scores[:, 2] = scalar_science * new_scores[:, 2]
print("new scores:\n", new_scores)
print("\n")

weight_vector_2 = np.array([[0.4], [0.2], [0.3], [0.1]])
final_grades_2 = new_scores @ weight_vector_2
#final_grade = np.dot(scores, weight_vector)
print("The final_grades:", final_grades_2)

new scores:
 [[ 82  71 231  55]
 [ 50  45 237  82]
 [ 59  68 216  53]
 [ 30  70 165  64]
 [ 72  83 195  87]]


The final_grades: [[121.8]
 [108.3]
 [107.3]
 [ 81.9]
 [112.6]]


In [105]:
student_3_score = new_scores[2:3]
student_4_score = new_scores[3:4]

print("Student_3 Score vector:",student_3_score)
print("\n")
print("Student_4 Score vector:",student_4_score)

compare_scores_2 = student_3_score - student_4_score
print("\n")
print("comparing student (3 & 4) vector score", compare_scores_2)

Student_3 Score vector: [[ 59  68 216  53]]


Student_4 Score vector: [[ 30  70 165  64]]


comparing student (3 & 4) vector score [[ 29  -2  51 -11]]


In [85]:
'''
In math - student 3 performs better
In english - student 4 performs better
In Science - student 3 performs better
In chemistry - student 4 performs better


'''

'\nIn math - student 3 performs better\nIn english - student 4 performs better\nIn Science - student 3 performs better\nIn chemistry - student 4 performs better\n\n\n'