 $ Let  A=\begin{bmatrix}2&-1\cr0&3\end{bmatrix}$ ,    $B=\begin{bmatrix}1&4\cr-2&5\end{bmatrix}$
and let the scalars  (c = 2), (d = 3). 

1. Compute (cA), (dB), and (c+d)A

        Solution


In [24]:
import numpy as np

A = np.array([[2, -1], 
              [0, 3]])

B = np.array([[1, 4], 
              [-2, 5]])
Scalar_c = 2
Scalar_d = 3

cA = Scalar_c * A
dB = Scalar_d * B
mat_asso = (Scalar_c + Scalar_d)* A


print("Matrix A:\n", A)
print('\n')
print("Matrix B:\n", B)
print('\n')
print("The result of cA:\n", cA)
print('\n')
print("The result of dB:\n", dB)
print('\n')
print("The result of (c+d)A:\n", mat_asso)

Matrix A:
 [[ 2 -1]
 [ 0  3]]


Matrix B:
 [[ 1  4]
 [-2  5]]


The result of cA:
 [[ 4 -2]
 [ 0  6]]


The result of dB:
 [[ 3 12]
 [-6 15]]


The result of (c+d)A:
 [[10 -5]
 [ 0 15]]


2. Using the results gotten , Verify the scalar Multiplication Properties

Solution

i. Associativity of scalar multiplication
(c.d)A = c.(dA)


In [25]:
assoc_1 = (Scalar_c * Scalar_d) * A
assoc_2 = Scalar_c * (Scalar_d * A)

print("The result of (c.d)A:\n", assoc_1)
print('\n')
print("The result of c.(dA):\n", assoc_2)
print('\n')
print("Associativity of scalar multiplication of (c.d)A = c.(dA):", np.array_equal(assoc_1, assoc_2))

The result of (c.d)A:
 [[12 -6]
 [ 0 18]]


The result of c.(dA):
 [[12 -6]
 [ 0 18]]


Associativity of scalar multiplication of (c.d)A = c.(dA): True


ii. Distributivity over Matrix Addition
c(A + B) =cA + cB


In [26]:
dist_1 = Scalar_c * (A + B)
dist_2 = Scalar_c * A + Scalar_c * B

print("The result of c(A + B):\n", dist_1)
print('\n')
print("The result of cA + cB:\n", dist_2)
print('\n')
print("Distributivity over matrix c(A + B)=  cA + cB:", np.array_equal(dist_1, dist_2))

The result of c(A + B):
 [[ 6  6]
 [-4 16]]


The result of cA + cB:
 [[ 6  6]
 [-4 16]]


Distributivity over matrix c(A + B)=  cA + cB: True


iii. Distributivity over Scalar Addition
(c + d)A = cA + dA

In [27]:
dist_scal_1 = (Scalar_c + Scalar_d) * A 
dist_scal_2 = Scalar_c * A + Scalar_d * A

print("The result of (c + d)A:\n", dist_scal_1)
print('\n')
print("The result of cA + dA:\n", dist_scal_2)
print('\n')
print("Distributivity over Scalar Addition c(A + B)=  cA + cB:", np.array_equal(dist_scal_1, dist_scal_2))

The result of (c + d)A:
 [[10 -5]
 [ 0 15]]


The result of cA + dA:
 [[10 -5]
 [ 0 15]]


Distributivity over Scalar Addition c(A + B)=  cA + cB: True


3. Find the transpose of both matrices

Solution

The rows becomes the columns and columns become the rows


In [30]:
print("Matrix A:\n", A)
print('\n')
print("Matrix B:\n", B)
print('\n')
print("\nTranspose A^T:\n", A.T)
print('\n')
print("\nTranspose B^T:\n", B.T)


Matrix A:
 [[ 2 -1]
 [ 0  3]]


Matrix B:
 [[ 1  4]
 [-2  5]]



Transpose A^T:
 [[ 2  0]
 [-1  3]]



Transpose B^T:
 [[ 1 -2]
 [ 4  5]]


4, Check if (A) and (B) are invertible by computing their determinants. if they are invertible  find $A^{-1}$ and $B^{-1}$

Solution

Determinant of A

In [31]:
print("Matrix A:\n", A)
print('\n')
print("Matrix B:\n", B)
print('\n')
print("\nDeterminant |A|:", np.linalg.det(A))
print('\n')
print("\nDeterminant |B|:", np.linalg.det(B))

Matrix A:
 [[ 2 -1]
 [ 0  3]]


Matrix B:
 [[ 1  4]
 [-2  5]]



Determinant |A|: 6.0



Determinant |B|: 13.0


Since the $|A|$  and $|B|$ !=0, then the two matrices are invertible.

In [38]:
print("\nInverse A^(-1):\n'", np.linalg.inv(A))
print('\n')
print("\nInverse B^(-1):\n'", np.linalg.inv(B))
print('\n')

Id_mat_a = A @ np.linalg.inv(A)
print("\nInverse A^(-1) x A = I:\n", Id_mat_a)

Id_mat_b = B @ np.linalg.inv(B)
print("\nInverse B^(-1) x B = I:\n", Id_mat_b)


Inverse A^(-1):
' [[0.5        0.16666667]
 [0.         0.33333333]]



Inverse B^(-1):
' [[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]



Inverse A^(-1) x A = I:
 [[1. 0.]
 [0. 1.]]

Inverse B^(-1) x B = I:
 [[1. 0.]
 [0. 1.]]
